INSERT INTO MOVIE (`TITLE`, `MOVIE_ID`) VALUES ('The Fast and the Furious', 'tt0232500');
INSERT INTO MOVIE (`TITLE`, `MOVIE_ID`) VALUES ('2 Fast 2 Furious', 'tt0322259');
INSERT INTO MOVIE (`TITLE`, `MOVIE_ID`) VALUES ('The Fast and the Furious: Tokyo Drift', 'tt0463985');
INSERT INTO MOVIE (`TITLE`, `MOVIE_ID`) VALUES ('Fast & Furious', 'tt1013752');
INSERT INTO MOVIE (`TITLE`, `MOVIE_ID`) VALUES ('Fast Five', 'tt1596343');
INSERT INTO MOVIE (`TITLE`, `MOVIE_ID`) VALUES ('Fast & Furious 6', 'tt1905041');
INSERT INTO MOVIE (`TITLE`, `MOVIE_ID`) VALUES ('Furious 7', 'tt2820852');
INSERT INTO MOVIE (`TITLE`, `MOVIE_ID`) VALUES ('The Fate of the Furious', 'tt4630562');